
-- 区域
DROP TABLE IF EXISTS ord_region;
CREATE TABLE ord_region (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(100) DEFAULT '' COMMENT '名称',
  note  VARCHAR(255) DEFAULT '' COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP   NOT NULL COMMENT '创建时间',
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL COMMENT '删除时间'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='区域';

-- 支行
DROP TABLE IF EXISTS ord_branch;
CREATE TABLE ord_branch (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(100) DEFAULT '' COMMENT '名称',
  pid BIGINT NOT NULL DEFAULT 1 COMMENT '父级编号',
  region_id BIGINT NOT NULL DEFAULT 1 COMMENT '区域id',
  org_code VARCHAR(20) DEFAULT '' COMMENT '机构编号',
  note  VARCHAR(255) DEFAULT '' COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP   NOT NULL COMMENT '创建时间',
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL COMMENT '删除时间'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='支行';

-- 用户-支行
DROP TABLE IF EXISTS ord_user_branch;
CREATE TABLE ord_user_branch (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 1 COMMENT '用户id',
  branch_id BIGINT NOT NULL DEFAULT 1 COMMENT '支行id'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='用户-支行';

--  产品
DROP TABLE IF EXISTS ord_product;
CREATE TABLE ord_product (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(100) DEFAULT '' COMMENT '名称',
  category     VARCHAR(100) DEFAULT '' COMMENT '品类',
  price  BIGINT NOT NULL DEFAULT 0 COMMENT '价格',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP   NOT NULL COMMENT '创建时间',
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL COMMENT '删除时间'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='产品';

--  收货地址
DROP TABLE IF EXISTS ord_address;
CREATE TABLE ord_address (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id  BIGINT NOT NULL DEFAULT 0 COMMENT '用户id',
  name       VARCHAR(100) DEFAULT '' COMMENT '收货人姓名',
  spare_name VARCHAR(100) DEFAULT '' COMMENT '备用收货人姓名',
  province_id  BIGINT NOT NULL DEFAULT 0 COMMENT '省份编号',
  city_id  BIGINT NOT NULL DEFAULT 0 COMMENT '市编号',
  county_id  BIGINT NOT NULL DEFAULT 0 COMMENT '县/区编号',
  street VARCHAR(500) NOT NULL DEFAULT '' COMMENT '街道',
  zip_code VARCHAR(20) NOT NULL DEFAULT '' COMMENT '邮编',
  phone VARCHAR(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  spare_phone VARCHAR(20) DEFAULT '' COMMENT '备用电话',
  is_default INT DEFAULT 0 NOT NULL COMMENT '默认地址0',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP   NOT NULL COMMENT '创建时间',
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL COMMENT '删除时间'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='收货地址';

-- 订单
DROP TABLE IF EXISTS ord_order;
CREATE TABLE ord_order (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code   VARCHAR(100) NOT NULL DEFAULT '' COMMENT '订单编码',
  user_id BIGINT NOT NULL DEFAULT 0 COMMENT '用户编号',
  branch_id BIGINT NOT NULL DEFAULT 0 COMMENT '支行编号',
  address_id BIGINT NOT NULL DEFAULT 0 COMMENT '收货地址编号',
  total_pay BIGINT NOT NULL DEFAULT 0 COMMENT '总金额',
  actual_pay BIGINT NOT NULL DEFAULT 0 COMMENT '实际金额',
  state INT NOT NULL DEFAULT 0 COMMENT '订单状态:-1已取消，0已新建，1已接收，2已发货，3已收货，4已支付',
  note  VARCHAR(255) DEFAULT '' COMMENT '备注',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP   NOT NULL COMMENT '创建时间',
  delivered_at TIMESTAMP NULL COMMENT '期望发货时间',
  actual_delivered_at TIMESTAMP NULL COMMENT '实际发货时间',
  payed_at TIMESTAMP NULL COMMENT '支付时间',
  receipted_at TIMESTAMP NULL COMMENT '收货/完成时间',
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  deleted_at TIMESTAMP NULL COMMENT '删除时间'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='订单';

-- 订单和产品的关联
DROP TABLE IF EXISTS ord_order_product;
CREATE TABLE ord_order_product (
  id         BIGINT   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL DEFAULT 0 COMMENT '订单编号',
  product_id BIGINT NOT NULL DEFAULT 0 COMMENT '产品id',
  num INT NOT NULL  DEFAULT 1 COMMENT  '产品数量'
) ENGINE =InnoDB DEFAULT CHARSET =utf8 COMMENT ='订单-产品';
